title: 黄博 Bo Huang
logo: /assets/img/IMG_5895_副本中.png
description: A graduate student of BUCT, currently focus on a cross-disciplinary research project that combines MS & CS
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one